### ISSUE TITLE
Robot cannot be loaded

### ISSUE THREAD

**Issue by mohamadmahdavian** [stephane-caron/lipm_walking_controller#18]
Hi Dr. Caron,

We are planning to import our own robot to the system (both Choreonoid and V-rep) and we made wrl and other configuration files similar to HRP4. We have also modified the mc_rtc.conf file and change the MainRobot to our robot "Beta1_v4" and created the Beta1_v4_description directory. in the ros catkin_ws But it does not seem to be working fine since both mc_vrep and MCUDPControl fail to load the robot showing the following error:

Trying to use Beta1_v4 as main robot but this robot cannot be loaded
Main robot not available
terminate called after throwing an instance of 'std::runtime_error'
  what():  Main robot not available
Aborted (core dumped)

I have reviewed the mc_rtc code and found out that in some test cases, there are some test robots created using a format:

struct ThrowingRobot : public mc_rbdyn::RobotModule

Do we need to create such a file describing our robot? if so, where do we have to put the file and how should it be implemented?

**Comment by stephane-caron** [comment]
Hi @mohamadmahdavian. Your question is related to mc_rtc rather than the lipm_walking_controller, therefore you should ask it on the [mc_rtc issue tracker](https://gite.lirmm.fr/multi-contact/mc_rtc/issues). You can tell the difference by looking for the following message in the terminal:
```
Create controller LIPMWalking
```
Everything before this message comes from mc_rtc.
