### ISSUE TITLE
ZMP during the DSP

### ISSUE THREAD

**Issue by Saeed-Mansouri** [stephane-caron/lipm_walking_controller#56]
Hi Dr. Caron,

As far as I know, the plane of the support foot is considered to calculate the zmp of the pendulum (`pendulum.zpm()`) during the DSP. However, for estimating the zmp of the stabilizer (`stabilizer.zpm()`) during the DSP, you considered the average of the left and right foot planes (`zmpframe_`). I think that beacuse of this inconsistency that occurs during walking on the stair, the below term of `Stabilizer::computeDesiredWrench()` should be modified.

`zmpError_ = pendulum_.zmp() - measuredZMP_;`

**Comment by stephane-caron** [comment]
That's right, that's why there is a comment in the code next to the line you mention :wink: 
```c++
zmpError_ = pendulum_.zmp() - measuredZMP_; // XXX: both in same plane?
```
The two are in the same plane during single support, but during double support, the pendulum ZMP is computed in the previous contact frame (see `states/DoubleSupport.cpp`) while the measured ZMP is computed in a "ZMP frame" midway between the two contact frames (see `Stabilizer.cpp`).

The discrepancy affects the DCM derivative term (which was disabled on HRP-4 in 2019, but active on HRP-2Kai) and only applies during stair climbing. The DCM derivative term is not so impactful but this could yield some undesired reactions during stair climbing.

@arntanguy @gergondet FYI. This is still around [jrl-umi3218/lipm_walking_controller](https://github.com/jrl-umi3218/lipm_walking_controller/).

There are two straightforward ways things to try from there:
1. Compute the measured ZMP in the previous contact frame (straightforward to implement)
2. Compute the pendulum ZMP in the midway ZMP frame (requires a bit of frame passing, nothing too hard)

@Saeed-Mansouri thanks for pointing this out :+1:
