### ISSUE TITLE
Stiffness and Damping Effect in the Foot Contact Controller Perfomance

### ISSUE THREAD

**Issue by Taherifar** [stephane-caron/lipm_walking_controller#60]
Hi Dr. Caron,
I have recently reviewed the [discussion](https://scaron.info/publications/icra-2019.html) on the "Stair Climbing Stabilization of the HRP-4 Humanoid Robot using Whole-body Admittance Control" paper. It was mentioned that the damping control is used instead of acceleration-based controller in the LIPM controller but the reason of that is not still clear for me. So, my questions are as listed below:
1- It is mentioned that the KΔθ≫BΔθ` in your application. Generally, Is it a must for the contact to have large stiffness and low damping to have stable damping controller?
2- I have done some simulation based on  [Kajita et al. (2001)](https://ieeexplore.ieee.org/document/933139), and it showed that in the presence of damping, the controller would be stable and even damping can reduce torque tracking error and improves the performance. Based on my simulation the foot contact should be designed such that the damping be as much as possible in order to increase the performance of the foot contact control. Is this an acceptable result?Are you agree with it?
3- Would you please explain why did you use the damping controller instead of acceleration-based controller?

**Comment by stephane-caron** [comment]
### Why use the damping controller?

Large stiffness and low damping were rather a design choice that came with the robots we worked with. The second-order model with both stiffness `K` and damping `B` coefficients has more parameters to tune, but if `KΔθ ≫ BΔdot(θ)` this more complex model will anyway behave like a first-order model. Let us apply [Occam's razor](https://en.wikipedia.org/wiki/Occam%27s_razor) then: using the first-order model, we get similar performance with less parameters to tune and simpler code to maintain :wink: 

I hope this helps with your questions 1 and 3. Regarding your question 2:

### Shall we try moving away from high-stiffness low-damping at the contact interface?

Absolutely: moving away from the "high stiffness low damping" setting makes sense in my opinion. We tried moving away from this setting when [walking on gravel with soft soles](https://hal.archives-ouvertes.fr/hal-01576516/document): the soles had a Young's modulus of 0.32 MPa (versus 5 MPa in previous works and I-don't-know-how-much for the default hard robot soles) meaning we reduced `K` rather than increase `B`. (We still walked on hard floor though.) I see two observations from this work that may be relevant here:

- The interaction with the ground after impact had more (ankle displacement to reaction force change) delay, which is not great for balance control where we want to maximize the force control bandwidth (_i.e._, when the stabilizer outputs a desired contact wrench, this wrench is realized as fast as possible). That's one thing to look at: maybe with high `K` and increased `B` we can reach a better sweet spot. 
- However foot impacts at touchdown were better mitigated. Walking controllers typically touchdown earlier than expected at every step, which incurs undesired CoM velocity disturbances (foot impacts after they propagate across the kinematic chain). But with the soft soles these impacts were lower. That's another thing to look at, maybe increasing `B` helps with the impact but for a given `K` we cannot go below some `minimumImpact(K)`.

Hoping this helps!
